import type { Metadata } from "next";
import "./globals.css";
import SessionProvider from "../context/SessionProvider";
import { InvestmentProvider } from "@/context/useInvestment";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-sans">
        <SessionProvider>
          <InvestmentProvider>{children}</InvestmentProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
